### ISSUE TITLE
Where to download the datasets?

### ISSUE THREAD

**Issue by nuomizai** [lanyavik/BAIL#2]
Where can I download the datasets like HOPPER B1 and SAC HOPPER B2? Or is there any reference code that I can use to generate the batch?

**Comment by watchernyu** [comment]
Hi! Thanks for posting the issue, we now have an optimized version of the buffers, which are much smaller than the original dataset (but the content is the same, just in a different format), they can be found here (about 28 GB in total): 

https://drive.google.com/drive/folders/1pjHodByRE0UelFJ0e1cZ2oKhffIsxu3d?usp=sharing

You can load them with joblib, the loaded object is a dictionary, and then each entry is a NumPy array (sample code below). Hope that helps! 
```
import joblib
d = joblib.load('DDPG_Final_Sigma0.5_Walker2d-v2_b1.pkl')
for key in d:
    print(key)
    print(d[key].shape)

""" output:
observations
(1000000, 17)
next_observations
(1000000, 17)
actions
(1000000, 6)
rewards
(1000000,)
dones
(1000000,)
"""

```
